import React from 'react';
import { ShieldAlert, CheckCircle2, FileText } from 'lucide-react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-900 text-slate-400 text-xs border-t border-slate-800 mt-auto">
      {/* Statutory Disclaimer Banner */}
      <div className="bg-slate-950 border-b border-slate-800 py-3 px-4 sm:px-6">
        <div className="max-w-7xl mx-auto flex items-start space-x-3 text-slate-400">
          <ShieldAlert className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
          <p className="leading-relaxed text-[11px]">
            <strong className="text-slate-200">Statutory Notice & AI Advisory Role:</strong> Automated scrutinies generated by PlanSanction are based on the Tamil Nadu Combined Development and Building Rules, 2019 (TNCDBR). The AI evaluation is an advisory technical aid. Final planning permission and building permits are strictly granted under the statutory authority of the designated Municipal Commissioner / Executive Town Planning Officer.
          </p>
        </div>
      </div>

      {/* Main Footer Links & Jurisdiction Info */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <div>
            <div className="text-sm font-semibold text-white mb-2">PlanSanction TN</div>
            <p className="text-xs text-slate-400 leading-relaxed">
              Integrated Online Building Plan Scrutiny & Sanction System for Namakkal District Municipalities & Town Panchayats.
            </p>
            <div className="mt-3 text-[11px] text-slate-500 font-mono">
              Portal Release v2.4 • TNCDBR 2019 Standard
            </div>
          </div>

          <div>
            <div className="text-xs font-semibold text-slate-200 uppercase tracking-wider mb-2">
              Namakkal Taluk Jurisdictions
            </div>
            <ul className="space-y-1 text-slate-400 text-xs">
              <li>• Tiruchengode Municipality (TCG)</li>
              <li>• Rasipuram Municipality (RSP)</li>
              <li>• Kumarapalayam Municipality (KMP)</li>
              <li>• Paramathi-Velur Town Panchayat (PMV)</li>
            </ul>
          </div>

          <div>
            <div className="text-xs font-semibold text-slate-200 uppercase tracking-wider mb-2">
              Statutory References
            </div>
            <ul className="space-y-1 text-slate-400 text-xs">
              <li>• TNCDBR 2019 Rule 35 (FSI & Coverage)</li>
              <li>• TNCDBR 2019 Rule 38 (Setback Norms)</li>
              <li>• TNCDBR 2019 Rule 42 (Mandatory Parking)</li>
              <li>• Tamil Nadu RWH Act Section 240-A</li>
            </ul>
          </div>

          <div>
            <div className="text-xs font-semibold text-slate-200 uppercase tracking-wider mb-2">
              Support & Helpdesk
            </div>
            <p className="text-xs text-slate-400">
              District Planning Authority Cell<br />
              Collectorate Master Complex, Namakkal - 637003<br />
              Helpline: 04286 - 280001 / 280002<br />
              Email: support.nmk@plansanction.tn.gov.in
            </p>
          </div>
        </div>

        <div className="border-t border-slate-800 mt-8 pt-4 flex flex-col sm:flex-row items-center justify-between text-[11px] text-slate-500">
          <div>
            © {new Date().getFullYear()} Directorate of Town and Country Planning, Government of Tamil Nadu.
          </div>
          <div className="mt-2 sm:mt-0 flex space-x-4">
            <span className="hover:text-slate-400 cursor-pointer">Security & Privacy Policy</span>
            <span>•</span>
            <span className="hover:text-slate-400 cursor-pointer">Terms of Sanction</span>
            <span>•</span>
            <span className="hover:text-slate-400 cursor-pointer">Public Grievances</span>
          </div>
        </div>
      </div>
    </footer>
  );
};
